FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "Gaumata_Dairy.csproj"
RUN dotnet build "Gaumata_Dairy.csproj" -c Release -o /app/build
RUN dotnet publish "Gaumata_Dairy.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Gaumata_Dairy.dll"]
